addSbtPlugin("com.geirsson"      % "sbt-scalafmt"         % "1.5.1")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"         % "0.9.1")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("com.github.gseitz" % "sbt-release"          % "1.0.11")
addSbtPlugin("au.com.onegeek"    %% "sbt-dotenv"          % "1.2.58")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"          % "0.3.2")
